// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgqIlLyv744SAZzilmIQLeIf1cOz9IWKs',
    appId: '1:444354096088:android:d218785a00d6d52173a0ad',
    messagingSenderId: '444354096088',
    projectId: 'fishpond-suviko',
    storageBucket: 'fishpond-suviko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnWW2vMLid1V-ThFbv-jVdtNK5oBziFQw',
    appId: '1:444354096088:ios:a8d1dc71ab68f4fe73a0ad',
    messagingSenderId: '444354096088',
    projectId: 'fishpond-suviko',
    storageBucket: 'fishpond-suviko.firebasestorage.app',
    androidClientId: '444354096088-edioceso1fa3kls5cqn94gbjnp8cenqs.apps.googleusercontent.com',
    iosClientId: '444354096088-4f57g5dsc59k7bb44bstka1vhlf1hm0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishpond',
  );
}
